'use strict';
/* S0 Acceptance Gate — Deterministic build/copy mechanism (owner decision I-1).
 *
 * Proves that data/canonical/*.json on disk is exactly what
 * scripts/build-canonical-data.js produces from the authority files
 * right now — i.e. the runtime copy was generated by the sanctioned
 * mechanism, not hand-maintained, and re-running the build is a no-op. */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const build = require(path.join(__dirname, '..', '..', 'scripts', 'build-canonical-data.js'));

test('build script is a pure function: re-running it reproduces the on-disk copy for both files', () => {
  for (const filename of build.FILES) {
    const expected = build.buildOne(filename);
    const actualOnDisk = fs.readFileSync(path.join(build.RUNTIME_DIR, filename), 'utf8');
    assert.equal(actualOnDisk, expected, `data/canonical/${filename} does not match deterministic build output — possible manual edit/drift`);
  }
});

test('canonicalize() is deterministic for a fixed object regardless of key insertion order source', () => {
  const a = { z: 1, a: 2 };
  const b = { a: 2, z: 1 };
  // JSON.stringify preserves insertion order for string keys; this test
  // documents that canonicalize is a straightforward deterministic
  // serialization, not that key order is normalized.
  assert.equal(build.canonicalize(a), '{\n  "z": 1,\n  "a": 2\n}\n');
  assert.equal(build.canonicalize(b), '{\n  "a": 2,\n  "z": 1\n}\n');
});
